name: CI Workflow with MongoDB and Docker

on:
  push:
    branches:
      - main  # o cualquier otra rama que desees
  pull_request:
    branches:
      - main  # o cualquier otra rama que desees

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017  # Exponer el puerto 27017 para MongoDB
        options: --health-cmd='curl --silent --fail localhost:27017' --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # Paso para configurar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso para asegurarse de que MongoDB está listo para aceptar conexiones
      - name: Wait for MongoDB to be ready
        run: |
          while ! curl --silent --fail localhost:27017; do
            echo "Waiting for MongoDB to be ready..."
            sleep 2
          done
          echo "MongoDB is ready!"

      # Paso para ejecutar pruebas o tareas (si tienes alguna de este tipo)
      - name: Run MongoDB test
        run: |
          docker exec -i mongodb mongo --eval 'db.test.insert({ test: "value" })'
          # Agrega tus pruebas o tareas aquí

      # Paso para detener y limpiar los contenedores
      - name: Shutdown containers
        run: |
          docker-compose down || true
