name: CI Workflow with Redis and Docker

on:
  push:
    branches:
      - main  # o la rama que desees
  pull_request:
    branches:
      - main  # o la rama que desees

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379  # Conectar a Redis en el puerto 6379
        options: --health-cmd='redis-server --test-memory' --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # Paso para configurar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso para configurar Docker Compose
      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d  # Levanta el contenedor Redis

      # Paso para ejecutar pruebas o tareas (si tienes alguna de este tipo)
      - name: Run Redis commands
        run: |
          docker-compose exec -T redis redis-cli PING  # Ejecuta un comando Redis de prueba
          # Aquí puedes agregar otras tareas o pruebas

      # Paso para detener y limpiar los contenedores
      - name: Shutdown containers
        run: |
          docker-compose down
